version: "3"
services:
  #Node Service
  node:
    image: node:14.15-buster
    container_name: higher-data-node
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: node
      SERVICE_TAGS: dev
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
    working_dir: /usr/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/usr/app
    #entrypoint: ./on-start.sh
    networks:
      - app-network

  #Mongo Service
  mongo:
    image: mongo:latest
    container_name: higher-data-mongo
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:27017"
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mongo
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - /data/db
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge


